# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Coding Challenge: NYC Schools' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coding Challenge: NYC Schools

  
    # Pods for testing
pod 'Alamofire', '~> 4.5'
pod 'AlamofireImage', '~> 3.0'
 

end
